name: Java Maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Validate
        run: mvn validate

      - name: Compile
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

      - name: Check Files
        run: |
          pwd
          echo "===== PROJECT FILES ====="
          ls -la
          echo "===== TARGET DIRECTORY ====="
          ls -la target || true
          echo "===== ALL JAR FILES ====="
          find . -name "*.jar"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-application
          path: target/*.jar
